terraform {
  required_version = ">= 1.5.0"

  # Connect to Terraform Cloud (HCP Terraform)
  cloud {
    organization = "sigbl"

    workspaces {
      name = "development" # Replace with your exact workspace name if different
    }
  }

  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.4.0"
    }
  }
}

provider "local" {}

# Call our custom module for each environment using a map of configurations
module "environments" {
  source = "./modules/env_config"

  for_each = {
    development = 1
    staging     = 2
    production  = 5
  }

  environment_name = each.key
  project_name     = "dsp-ecommerce-infra"
  replica_count    = each.value
}

# Output the results coming from the module
output "environment_file_paths" {
  value       = { for env, mod in module.environments : env => mod.file_path }
  description = "Paths to environment files generated by our custom module."
}